// generated by stringer -type=Code; DO NOT EDIT

package turms

import "fmt"

const (
	_Code_name_0 = "HelloCodeWelcomeCodeAbortCodeChallengeCodeAuthenticateCodeGoodbyeCode"
	_Code_name_1 = "ErrorCode"
	_Code_name_2 = "PublishCodePublishedCode"
	_Code_name_3 = "SubscribeCodeSubscribedCodeUnsubscribeCodeUnsubscribedCodeEventCode"
	_Code_name_4 = "CallCodeCancelCodeResultCode"
	_Code_name_5 = "RegisterCodeRegisteredCodeUnregisterCodeUnregisteredCodeInvocationCodeInterruptCodeYieldCode"
)

var (
	_Code_index_0 = [...]uint8{0, 9, 20, 29, 42, 58, 69}
	_Code_index_1 = [...]uint8{0, 9}
	_Code_index_2 = [...]uint8{0, 11, 24}
	_Code_index_3 = [...]uint8{0, 13, 27, 42, 58, 67}
	_Code_index_4 = [...]uint8{0, 8, 18, 28}
	_Code_index_5 = [...]uint8{0, 12, 26, 40, 56, 70, 83, 92}
)

func (i Code) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case i == 8:
		return _Code_name_1
	case 16 <= i && i <= 17:
		i -= 16
		return _Code_name_2[_Code_index_2[i]:_Code_index_2[i+1]]
	case 32 <= i && i <= 36:
		i -= 32
		return _Code_name_3[_Code_index_3[i]:_Code_index_3[i+1]]
	case 48 <= i && i <= 50:
		i -= 48
		return _Code_name_4[_Code_index_4[i]:_Code_index_4[i+1]]
	case 64 <= i && i <= 70:
		i -= 64
		return _Code_name_5[_Code_index_5[i]:_Code_index_5[i+1]]
	default:
		return fmt.Sprintf("Code(%d)", i)
	}
}
